### ISSUE TITLE
Documentation of "Properties"

### ISSUE THREAD

**Issue by erikbosch** [COVESA/ifex#75]
Noted that we have not described "type" (i.e. attribute/sensor/actuator) in https://github.com/COVESA/vehicle_service_catalog#namespace-list-object-properties, and it is also not included in the example in the README file (but is present in the comfort seat example file).

Also noted that "arraysize" is documented, but not listed as "Optional keys".

**Comment by gunnar-mb** [comment]
- typedef is now better described.  Documentation of fields are generated from the internal model ([ifex_ast.py](https://github.com/COVESA/ifex/blob/master/ifex/model/ifex_ast.py) using the [ifex_ast_doc.py](https://github.com/COVESA/ifex/blob/master/ifex/model/ifex_ast_doc.py) generator code.

>  it is also not included in the example in the README
- Examples are now also part of the specification generation.  They are not automatically syntax-checked however, which is another open topic =  #102

> Also noted that "arraysize" is documented, but not listed as "Optional keys".

Since we now have automatic generation of the documentation from the internal model, that guarantees that optionality and similar aspects are always specified correctly in the specification.  We can confidently say that this has therefore been fixed.
